name: Shipit

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags (Shipit requires it).
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps
        uses: bahmutov/npm-install@v1

      - name: Install Shipit deps
        uses: bahmutov/npm-install@v1
        with:
          working-directory: shipit

      - name: Setup ssh agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_SHIPIT_PRIVATE_KEY }}

      - name: Run Shipit
        run: npm run shipit
